import { ThemeProvider } from "@/components/theme-provider";
import "../globals.css";
import LoggedOutOnly from "@/components/LoggedOutOnly";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LoginLayout({ children }) {
  return (
    <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange
    >
      <LoggedOutOnly>
      {children}
      </LoggedOutOnly>
    </ThemeProvider>
  );
}
