import { ThemeProvider } from "@/components/theme-provider";
import "@/app/globals.css";
import StudentLinks from "@/components/StudentLiks";
import LoggedInOnly from "@/components/LoggedInOnly";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function StudentLayout({ children }) {

  return (
    <LoggedInOnly>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <div className="container mx-auto bg-white mt-[4rem] pb-[4rem]">
          <div className="grid grid-cols-8">
            <div className="lg:col-span-2 md:col-span-3 col-span-full">
              <div className="m-6 md:border-r-2 md:border-b-0 border-b-4 border-gray-200">
                <StudentLinks />
              </div>
            </div>
            <div className="lg:col-span-6 md:col-span-5 col-span-full">
              <div className="m-6">
                {children}
              </div>
            </div>
          </div>
        </div>
      </ThemeProvider>
    </LoggedInOnly>
  );
}
