import { ThemeProvider } from "@/components/theme-provider";
import "@/app/globals.css";
import StudentLinks from "@/components/StudentLiks";
import LoggedInOnly from "@/components/LoggedInOnly";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function StudentLayout({ children }) {

  return (
    <LoggedInOnly>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <div className="container mx-auto bg-white mt-[4rem] pb-[4rem]">
          <div className="grid grid-cols-4">
            <div className="col-span-1">
              <div className="m-6 border-r-2 border-gray-200">
                <StudentLinks />
              </div>
            </div>
            <div className="col-span-3">
              <div className="m-6">
                {children}
              </div>
            </div>
          </div>
        </div>
      </ThemeProvider>
    </LoggedInOnly>
  );
}
