import { ThemeProvider } from "@/components/theme-provider";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/sections/Header";
import TopHeader from "@/components/sections/TopHeader";
import Footer from "@/components/sections/Footer";
import BottomFooter from "@/components/sections/BottomFooter";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >

          <TopHeader />
          <Header />
          <div className="grow">
            {children}
          </div>
          <Footer />
          <BottomFooter />
        </ThemeProvider>

      </body>
    </html>
  );
}
