import { ThemeProvider } from "@/components/theme-provider";
import "../globals.css";
import Header from "@/components/sections/Header";
import TopHeader from "@/components/sections/TopHeader";
import Footer from "@/components/sections/Footer";
import BottomFooter from "@/components/sections/BottomFooter";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange
    >

      <TopHeader />
      <Header />
      <div className="grow">
        {children}
      </div>
      <Footer />
      <BottomFooter />
    </ThemeProvider>
  );
}
