import { ThemeProvider } from "@/components/theme-provider";
import localFont from "next/font/local";
import "../globals.css";
import LoggedOutOnly from "@/components/LoggedOutOnly";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RegisterLayout({ children }) {
  return (
    <main className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen overflow-x-hidden`}>

      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <LoggedOutOnly>
          {children}
        </LoggedOutOnly>
      </ThemeProvider>
    </main>
  );
}
