import { ThemeProvider } from "@/components/theme-provider";
import localFont from "next/font/local";
import "../globals.css";
import LoggedOutOnly from "@/components/LoggedOutOnly";
import Skeleton from "@/components/ui/skeleton";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RegisterLayout({ children }) {
  return (
    <main className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen overflow-x-hidden`}>

      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <LoggedOutOnly skeleton={<div className="w-screen h-screen flex items-center justify-center"><Skeleton className="w-[24rem] h-[32rem]" /></div>}>
          {children}
        </LoggedOutOnly>
      </ThemeProvider>
    </main>
  );
}
